jobs:
  - job: Test
    pool:
      vmImage: 'ubuntu-20.04'
    variables:
      NODE_VERSION: 14.18.1
      SPRING_OUTPUT_ANSI_ENABLED: NEVER
      SPRING_JPA_SHOW_SQL: false
      JHI_DISABLE_WEBPACK_LOGS: true
      NG_CLI_ANALYTICS: 'false'
      JHI_E2E_HEADLESS: true

    steps:
      #----------------------------------------------------------------------
      # Install all tools and check configuration
      #----------------------------------------------------------------------
      - task: NodeTool@0
        inputs:
          versionSpec: $(NODE_VERSION)
        displayName: 'TOOLS: install Node.js'
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            sudo apt install ./google-chrome-stable_current_amd64.deb
        displayName: 'TOOLS: install Chrome'
      #----------------------------------------------------------------------
      # Tests
      #----------------------------------------------------------------------
      - task: Npm@1
        inputs:
          command: 'install'
        displayName: 'INSTALL: launch npm install'
      - script: |
          curl -Lo ./snyk $(curl -s https://api.github.com/repos/snyk/snyk/releases/latest | grep "browser_download_url.*snyk-linux" | cut -d ':' -f 2,3 | tr -d \" | tr -d ' ')
          chmod +x snyk
        displayName: 'INSTALL: Snyk CLI'
      - script: ./snyk test --all-projects || true
        displayName: 'CHECK: Snyk test'
        env:
          SNYK_TOKEN: $(SNYK_TOKEN)
      - script: ./snyk monitor --all-projects
        displayName: 'CHECK: Snyk monitor'
        env:
          SNYK_TOKEN: $(SNYK_TOKEN)
      - script: chmod +x mvnw
      - task: Npm@1
        inputs:
          command: 'custom'
          customCommand: ' run ci:backend:test'
        displayName: 'TESTS: backend'
      - task: PublishTestResults@2
        inputs:
          testResultsFormat: 'JUnit'
          testResultsFiles: '**/TEST-*.xml'
          searchFolder: '$(Build.SourcesDirectory)/target/test-results'
        condition: succeededOrFailed()
        displayName: 'TESTS: publish test results'
      - task: Npm@1
        inputs:
          command: 'custom'
          customCommand: ' run ci:frontend:test'
        displayName: 'TESTS: frontend'
      - task: PublishTestResults@2
        inputs:
          testResultsFormat: 'JUnit'
          testResultsFiles: '$(Build.SourcesDirectory)/target/test-results/TESTS-results-jest.xml'
        condition: succeededOrFailed()
        displayName: 'TESTS: publish test results'
      - task: Npm@1
        inputs:
          command: 'custom'
          customCommand: ' run java:jar:prod'
        displayName: 'TESTS: packaging'
      - task: Npm@1
        inputs:
          command: 'custom'
          customCommand: ' run ci:e2e:package'
        displayName: 'E2E: Package'
      - task: Npm@1
        inputs:
          command: 'custom'
          customCommand: ' run ci:e2e:prepare'
        displayName: 'E2E: Prepare'
      - task: Npm@1
        inputs:
          command: 'custom'
          customCommand: ' run ci:e2e:run'
        displayName: 'E2E: Run'
      - task: Npm@1
        inputs:
          command: 'custom'
          customCommand: ' run ci:e2e:teardown'
        displayName: 'E2E: Teardown'
