route:
  receiver: 'webhook'
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 2h

receivers:
  - name: 'webhook'
    webhook_configs:
      # For testing, create a sample alerting webhook at http://webhook.site/
      - url: 'https://webhook.site/c7c0c313-d900-4e9b-92d0-7469edec948a'
        send_resolved: true
